version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      MYSQL_DB: crypto-manager
    command: sh -c "npm install && npx ts-node-dev --respawn src/index.ts"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  db:
    image: mysql:9.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: crypto-manager
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
